version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - postgres
      - neo4j
      - ollama
    ports:
      - "8501:8501"
volumes:
  pgdata:
  neo4jdata:
