version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: writer
      POSTGRES_PASSWORD: writerpass
      POSTGRES_DB: writerdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  app:
    build: .
    command: ["python", "-m", "writeragents"]
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://writer:writerpass@postgres:5432/writerdb
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"

  ollama:
    build: .
    command: ["ollama", "serve", "--host", "0.0.0.0", "--context-size", "32768"]
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

volumes:
  pgdata:
  ollama:
