# Configuration for local mode
llm:
  endpoint: http://localhost:8000
  model: local-model
storage:
  database_url: sqlite:///memory.db
  redis_host: localhost
wba:
  candidate_limit: 3
story_structure:
  template: [act_i, act_ii, act_iii]
