# Configuration for local mode
llm:
  endpoint: http://ollama:11434
  model: qwen2.5:7b-instruct-q4_k_m
storage:
  database_url: sqlite:///memory.db
  redis_host: localhost
  redis_port: 6379
  redis_db: 0
wba:
  candidate_limit: 3
  classification_threshold: 0.8
story_structure:
  template: [act_i, act_ii, act_iii]
