# Configuration for networked mode
llm:
  endpoint: https://api.openai.com/v1
  model: gpt-4
  api_key: YOUR_API_KEY
storage:
  database_url: postgres://user:pass@db/writeragents
  redis_host: redis
wba:
  candidate_limit: 3
