# Configuration for networked mode
llm:
  endpoint: https://api.openai.com/v1
  model: gpt-4
  api_key: YOUR_API_KEY
storage:
  database_url: postgres://user:pass@db/writeragents
  redis_host: redis
  redis_port: 6379
  redis_db: 0
wba:
  candidate_limit: 3
  classification_threshold: 0.8
story_structure:
  template: [act_i, act_ii, act_iii]
